FROM python:3.9.0-slim-buster
COPY *.py ./
RUN python3 -m pip install pip==21.0.1 && \
    python3 -m pip install pandas && \
    python3 -m pip install psycopg2-binary && \
    python3 -m pip install sqlalchemy && \
    python3 -m pip install flask && \
    python3 -m pip install flask_cors && \
    python3 -m pip install numpy && \
    python3 -m pip install waitress && \
    python3 -m pip install networkx
EXPOSE 5000
ENTRYPOINT ["python3", "./main.py"]
