export default [
  {label: 'Select District', value: 'Select District'},
  {label: 'Mitte', value: 'Mitte'},
  {label: 'Friedrichshain-Kreuzberg', value: 'Friedrichshain-Kreuzberg'},
  {label: 'Pankow', value: 'Pankow'},
  {label: 'Charlottenburg-Wilmersdorf', value: 'Charlottenburg-Wilmersdorf'},
  {label: 'Spandau', value: 'Spandau'},
  {label: 'Steglitz-Zehlendorf', value: 'Steglitz-Zehlendorf'},
  {label: 'Tempelhof-Schöneberg', value: 'Tempelhof-Schöneberg'},
  {label: 'Neukölln', value: 'Neukölln'},
  {label: 'Treptow-Köpenick', value: 'Treptow-Köpenick'},
  {label: 'Marzahn-Hellersdorf', value: 'Marzahn-Hellersdorf'},
  {label: 'Lichtenberg', value: 'Lichtenberg'},
  {label: 'Reinickendorf', value: 'Reinickendorf'},
];
