FROM node:15.4.0-alpine3.12
# added curl for docker health
RUN apk update && apk upgrade && apk add --no-cache curl 
COPY getTokenApi.js ./
COPY package.json ./
COPY yarn.lock ./
RUN yarn --pure-lockfile
EXPOSE 3811
ENTRYPOINT ["node","./getTokenApi.js"]