// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: grpc/circles.proto

package grpc

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ReadCirclesParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Eventid string `protobuf:"bytes,1,opt,name=eventid,proto3" json:"eventid,omitempty"`
}

func (x *ReadCirclesParams) Reset() {
	*x = ReadCirclesParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_circles_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadCirclesParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCirclesParams) ProtoMessage() {}

func (x *ReadCirclesParams) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_circles_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCirclesParams.ProtoReflect.Descriptor instead.
func (*ReadCirclesParams) Descriptor() ([]byte, []int) {
	return file_grpc_circles_proto_rawDescGZIP(), []int{0}
}

func (x *ReadCirclesParams) GetEventid() string {
	if x != nil {
		return x.Eventid
	}
	return ""
}

type ResponseEventsCircles struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success      bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	EventCircles []*ResponseEventCircle `protobuf:"bytes,2,rep,name=eventCircles,proto3" json:"eventCircles,omitempty"`
}

func (x *ResponseEventsCircles) Reset() {
	*x = ResponseEventsCircles{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_circles_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseEventsCircles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseEventsCircles) ProtoMessage() {}

func (x *ResponseEventsCircles) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_circles_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseEventsCircles.ProtoReflect.Descriptor instead.
func (*ResponseEventsCircles) Descriptor() ([]byte, []int) {
	return file_grpc_circles_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseEventsCircles) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResponseEventsCircles) GetEventCircles() []*ResponseEventCircle {
	if x != nil {
		return x.EventCircles
	}
	return nil
}

type ResponseEventCircle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Eventid  string `protobuf:"bytes,1,opt,name=eventid,proto3" json:"eventid,omitempty"`
	Circleid string `protobuf:"bytes,2,opt,name=circleid,proto3" json:"circleid,omitempty"`
}

func (x *ResponseEventCircle) Reset() {
	*x = ResponseEventCircle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_circles_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseEventCircle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseEventCircle) ProtoMessage() {}

func (x *ResponseEventCircle) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_circles_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseEventCircle.ProtoReflect.Descriptor instead.
func (*ResponseEventCircle) Descriptor() ([]byte, []int) {
	return file_grpc_circles_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseEventCircle) GetEventid() string {
	if x != nil {
		return x.Eventid
	}
	return ""
}

func (x *ResponseEventCircle) GetCircleid() string {
	if x != nil {
		return x.Circleid
	}
	return ""
}

type ResponseEvents struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool             `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Events  []*ResponseEvent `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *ResponseEvents) Reset() {
	*x = ResponseEvents{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_circles_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseEvents) ProtoMessage() {}

func (x *ResponseEvents) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_circles_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseEvents.ProtoReflect.Descriptor instead.
func (*ResponseEvents) Descriptor() ([]byte, []int) {
	return file_grpc_circles_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseEvents) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResponseEvents) GetEvents() []*ResponseEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type ResponseEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Eventid string `protobuf:"bytes,1,opt,name=eventid,proto3" json:"eventid,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Year    int32  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	Month   int32  `protobuf:"varint,4,opt,name=month,proto3" json:"month,omitempty"`
	Day     int32  `protobuf:"varint,5,opt,name=day,proto3" json:"day,omitempty"`
	Hour    int32  `protobuf:"varint,6,opt,name=hour,proto3" json:"hour,omitempty"`
	Minute  int32  `protobuf:"varint,7,opt,name=minute,proto3" json:"minute,omitempty"`
}

func (x *ResponseEvent) Reset() {
	*x = ResponseEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_circles_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseEvent) ProtoMessage() {}

func (x *ResponseEvent) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_circles_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseEvent.ProtoReflect.Descriptor instead.
func (*ResponseEvent) Descriptor() ([]byte, []int) {
	return file_grpc_circles_proto_rawDescGZIP(), []int{4}
}

func (x *ResponseEvent) GetEventid() string {
	if x != nil {
		return x.Eventid
	}
	return ""
}

func (x *ResponseEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResponseEvent) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *ResponseEvent) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *ResponseEvent) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *ResponseEvent) GetHour() int32 {
	if x != nil {
		return x.Hour
	}
	return 0
}

func (x *ResponseEvent) GetMinute() int32 {
	if x != nil {
		return x.Minute
	}
	return 0
}

type ResponseUsers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool            `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Users   []*ResponseUser `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *ResponseUsers) Reset() {
	*x = ResponseUsers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_circles_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseUsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseUsers) ProtoMessage() {}

func (x *ResponseUsers) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_circles_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseUsers.ProtoReflect.Descriptor instead.
func (*ResponseUsers) Descriptor() ([]byte, []int) {
	return file_grpc_circles_proto_rawDescGZIP(), []int{5}
}

func (x *ResponseUsers) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResponseUsers) GetUsers() []*ResponseUser {
	if x != nil {
		return x.Users
	}
	return nil
}

type ResponseUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fcmtoken string `protobuf:"bytes,1,opt,name=fcmtoken,proto3" json:"fcmtoken,omitempty"`
}

func (x *ResponseUser) Reset() {
	*x = ResponseUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_circles_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseUser) ProtoMessage() {}

func (x *ResponseUser) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_circles_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseUser.ProtoReflect.Descriptor instead.
func (*ResponseUser) Descriptor() ([]byte, []int) {
	return file_grpc_circles_proto_rawDescGZIP(), []int{6}
}

func (x *ResponseUser) GetFcmtoken() string {
	if x != nil {
		return x.Fcmtoken
	}
	return ""
}

var File_grpc_circles_proto protoreflect.FileDescriptor

var file_grpc_circles_proto_rawDesc = []byte{
	0x0a, 0x12, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x2d, 0x0a, 0x11, 0x52, 0x65,
	0x61, 0x64, 0x43, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x69, 0x64, 0x22, 0x70, 0x0a, 0x15, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x43, 0x69, 0x72, 0x63, 0x6c,
	0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x3d, 0x0a, 0x0c,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x43, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x43, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x52, 0x0c, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x43, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x73, 0x22, 0x4b, 0x0a, 0x13, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x43, 0x69, 0x72, 0x63,
	0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x63, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x69, 0x64, 0x22, 0x57, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x2b, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x22, 0xa5, 0x01, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x64,
	0x61, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x64, 0x61, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x6f, 0x75, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x68, 0x6f, 0x75,
	0x72, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x6d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x22, 0x53, 0x0a, 0x0d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x28, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x22, 0x2a,
	0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1a,
	0x0a, 0x08, 0x66, 0x63, 0x6d, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x66, 0x63, 0x6d, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x32, 0xef, 0x01, 0x0a, 0x15, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x43, 0x69, 0x72,
	0x63, 0x6c, 0x65, 0x73, 0x12, 0x4b, 0x0a, 0x11, 0x52, 0x65, 0x61, 0x64, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x43, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x73, 0x12, 0x17, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x52, 0x65, 0x61, 0x64, 0x43, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x73, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x1a, 0x1b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x43, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x73, 0x22,
	0x00, 0x12, 0x3d, 0x0a, 0x0a, 0x52, 0x65, 0x61, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12,
	0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x43, 0x69, 0x72, 0x63, 0x6c,
	0x65, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x14, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x00,
	0x12, 0x4a, 0x0a, 0x18, 0x52, 0x65, 0x61, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x17, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x43, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x73, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x13, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x55, 0x73, 0x65, 0x72, 0x73, 0x22, 0x00, 0x42, 0x2d, 0x5a, 0x2b,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6f, 0x63, 0x6f, 0x74,
	0x72, 0x65, 0x65, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2d, 0x63, 0x69, 0x72, 0x63,
	0x6c, 0x65, 0x2d, 0x61, 0x70, 0x70, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_grpc_circles_proto_rawDescOnce sync.Once
	file_grpc_circles_proto_rawDescData = file_grpc_circles_proto_rawDesc
)

func file_grpc_circles_proto_rawDescGZIP() []byte {
	file_grpc_circles_proto_rawDescOnce.Do(func() {
		file_grpc_circles_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_circles_proto_rawDescData)
	})
	return file_grpc_circles_proto_rawDescData
}

var file_grpc_circles_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_grpc_circles_proto_goTypes = []interface{}{
	(*ReadCirclesParams)(nil),     // 0: grpc.ReadCirclesParams
	(*ResponseEventsCircles)(nil), // 1: grpc.ResponseEventsCircles
	(*ResponseEventCircle)(nil),   // 2: grpc.ResponseEventCircle
	(*ResponseEvents)(nil),        // 3: grpc.ResponseEvents
	(*ResponseEvent)(nil),         // 4: grpc.ResponseEvent
	(*ResponseUsers)(nil),         // 5: grpc.ResponseUsers
	(*ResponseUser)(nil),          // 6: grpc.ResponseUser
}
var file_grpc_circles_proto_depIdxs = []int32{
	2, // 0: grpc.ResponseEventsCircles.eventCircles:type_name -> grpc.ResponseEventCircle
	4, // 1: grpc.ResponseEvents.events:type_name -> grpc.ResponseEvent
	6, // 2: grpc.ResponseUsers.users:type_name -> grpc.ResponseUser
	0, // 3: grpc.ServicesEventsCircles.ReadEventsCircles:input_type -> grpc.ReadCirclesParams
	0, // 4: grpc.ServicesEventsCircles.ReadEvents:input_type -> grpc.ReadCirclesParams
	0, // 5: grpc.ServicesEventsCircles.ReadEventRegisteredUsers:input_type -> grpc.ReadCirclesParams
	1, // 6: grpc.ServicesEventsCircles.ReadEventsCircles:output_type -> grpc.ResponseEventsCircles
	3, // 7: grpc.ServicesEventsCircles.ReadEvents:output_type -> grpc.ResponseEvents
	5, // 8: grpc.ServicesEventsCircles.ReadEventRegisteredUsers:output_type -> grpc.ResponseUsers
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_grpc_circles_proto_init() }
func file_grpc_circles_proto_init() {
	if File_grpc_circles_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_circles_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadCirclesParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_circles_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseEventsCircles); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_circles_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseEventCircle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_circles_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseEvents); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_circles_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_circles_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseUsers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_circles_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_circles_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_circles_proto_goTypes,
		DependencyIndexes: file_grpc_circles_proto_depIdxs,
		MessageInfos:      file_grpc_circles_proto_msgTypes,
	}.Build()
	File_grpc_circles_proto = out.File
	file_grpc_circles_proto_rawDesc = nil
	file_grpc_circles_proto_goTypes = nil
	file_grpc_circles_proto_depIdxs = nil
}
